language: node_js
node_js:
- 6.2.1
env:
  - CXX=g++-4.8
services:
- mongodb
before_install:
- npm config set registry http://registry.npmjs.org/
- npm install -g bower
- sudo apt-get install ruby-full
- gem install compass --version ="1.0.3"
- gem install sass --version ="3.4.18"
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
install:
- npm install
- bower install
- ./node_modules/protractor/bin/webdriver-manager update --standalone
- ./node_modules/protractor/bin/webdriver-manager start --standalone &
before_script:
- npm install grunt-cli -g
- grunt
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start
- sleep 5
script:
  protractor tests/conf.js
deploy:
  provider: heroku
  api_key:
    secure: 29bce0f2-8df5-48c3-8448-c47c77c6cd7d
  app: bennyjrxyz
  on:
    repo: jrbenny35/mywebsitev3
